site_name: epf-transmitter

site_url: !ENV [SITE_URL, 'https://astrizhachuk.github.io/epf-transmitter']
repo_name: !ENV [REPO_NAME, 'astrizhachuk/epf-transmitter']
repo_url: !ENV [REPO_URL, 'https://github.com/astrizhachuk/epf-transmitter']
edit_uri: !ENV [EDIT_URI, 'edit/master/docs']

nav:
  - 'Описание': 'index.md'
  - 'Управление доставкой файлов': 'workflow.md'
  - 'Руководство пользователя': 'manual.md'
  - 'Разработка':
    - 'Разворачивание': 'deploy.md'
    - 'Участие в разработке': 'contributing.md'

theme: 
  name: material
  language: ru
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    # Light mode
    - teal: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.tabs
    - navigation.top
    - search.highlight
    - toc.integrate
    
extra:
  social:
    - icon: !ENV [SOCIAL_ICON, 'fontawesome/brands/github']
      link: !ENV [SOCIAL_LINK, 'https://github.com/astrizhachuk/epf-transmitter']
extra_css:
  - 'assets/stylesheets/extra.css'

plugins:
  - macros
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml
  - search:
      lang:
        - ru

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
