openapi: 3.0.1
info:
  title: Внешние отчеты и обработки (receiver)
  description: 'Управление внешними отчетами и обработками через HTTP сервис (REST). Receiver.'
  contact:
    email: a.strizhachuk@yandex.ru
  version: 1.0.0
servers:
- url: http://localhost/receiver/hs/gitlab
  description: Develop
paths:
  /version:
    get:
      summary: Версия конфигурации
      operationId: version
      responses:
        200:
          description: Версия конфигурации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              examples:
                foo:
                  summary: Версия конфигурации
                  value: {
                    "type": "info",
                    "message": "10.3.6.98"
                  }
  /switch:
    post:
      summary: Включить/отключить функционал загрузки внешнего отчета или обработки
      operationId: switch
      parameters:
      - name: Value
        in: header
        description: true - включить, false - отключить
        required: true
        schema:
          type: boolean
      requestBody:
        content: {}
        required: false
      responses:
        200:
          description: Текущее состояние
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              examples:
                enabled:
                  summary: Включено
                  value: {
                    "type": "info",
                    "message": "Включено"
                  }
                disabled:
                  summary: Отключено
                  value: {
                    "type": "info",
                    "message": "Отключено"
                  }
        400:
          description: Ошибочный запрос
        401:
          description: Не авторизован
        403:
          description: Доступ закрыт
      security:
      - access_token_receiver: []
  /update:
    post:
      summary: Обновить внешний отчет или обработку
      operationId: update
      parameters:
      - name: Name
        in: header
        description: Полное имя файла (с расширением)
        required: true
        schema:
          type: string
      requestBody:
        description: Внешний отчет или обработка в двоичном формате
        content:
          application/x-www-form-urlencoded:
            schema:
              format: binary
        required: true
      responses:
        200:
          description: Результат обновления
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              examples:
                true:
                  summary: Обновление успешно
                  value: {
                    "type": "info",
                    "message": "Любое сообщение..."
                  }
                false:
                  summary: Обновление не произошло
                  value: {
                    "type": "error",
                    "message": "Ошибка такая-то..."
                  }
        400:
          description: Ошибочный запрос
        401:
          description: Не авторизован
        403:
          description: Доступ закрыт
        423:
          description: Функционал отключен
      security:
      - access_token_receiver: []
components:
  schemas:
    response:
      type: object
      properties:
        type:
          type: string
          enum:
          - info
          - error
        message:
          type: string
  securitySchemes:
    access_token_receiver:
      type: apiKey
      name: Token
      in: header