name: SonarQube

on: [push, pull_request]

jobs:
  SonarScanner:
    if: github.repository == 'astrizhachuk/epf-transmitter'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup SonarQube scanner
      uses: warchant/setup-sonar-scanner@v3
    - name: Run SonarQube on push
      if: github.event_name == 'push'
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.projectVersion=$(grep -oPm1 "(?<=<version>)[^<]+" Transmitter/src/Configuration/Configuration.mdo)
        -Dsonar.host.url=https://sonar.openbsl.ru
        -Dsonar.branch.name=${GITHUB_REF#refs/heads/}
    - name: Run SonarQube on pull request
      if: github.event_name == 'pull_request'
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonar.openbsl.ru
        -Dsonar.projectVersion=$(grep -oPm1 "(?<=<version>)[^<]+" Transmitter/src/Configuration/Configuration.mdo)
        -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
        -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
        -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
